// GENERATED BY tools/gen_http_contract.py — DO NOT EDIT BY HAND.
//
// The HTTP contract of Scrutator, transcribed from the FastAPI application's own OpenAPI document
// (`scrutator.health.app.openapi()`), in the only shape the graph-verified-change verifier can
// diff: zod declarations and a string-literal union of the served routes
// (contract_diff.py reads *.ts only; it has no pydantic or OpenAPI extractor).
//
// Regenerate with `python3 tools/gen_http_contract.py`; `tests/test_http_contract.py` fails if this
// file and the application disagree.
//
// It is also a usable contract: a TypeScript consumer of this service can import these schemas.

import { z } from "zod";


export type ScrutatorRouteRequest =
  | "DELETE /v1/edges"
  | "DELETE /v1/index"
  | "DELETE /v1/ltm/source"
  | "DELETE /v1/memories"
  | "GET /health"
  | "GET /v1/chunks"
  | "GET /v1/edges/{chunk_id}"
  | "GET /v1/index/capability"
  | "GET /v1/index/rollback-capability"
  | "GET /v1/ltm/entities"
  | "GET /v1/ltm/events"
  | "GET /v1/ltm/graph"
  | "GET /v1/ltm/jobs/{job_id}"
  | "GET /v1/ltm/meta_facts"
  | "GET /v1/memories/stats"
  | "GET /v1/namespaces"
  | "GET /v1/navigate/outline"
  | "GET /v1/navigate/section"
  | "GET /v1/stats"
  | "POST /v1/chunk"
  | "POST /v1/dream/analyze"
  | "POST /v1/edges"
  | "POST /v1/edges/by-path"
  | "POST /v1/fetch"
  | "POST /v1/index"
  | "POST /v1/index/batch"
  | "POST /v1/index/capability-projection"
  | "POST /v1/ltm/ingest"
  | "POST /v1/ltm/recall"
  | "POST /v1/ltm/reflect"
  | "POST /v1/memories"
  | "POST /v1/memories/bulk"
  | "POST /v1/memories/recall"
  | "POST /v1/namespaces"
  | "POST /v1/search";


export const BatchIndexFailedSchema = z.object({
    source_path: z.string(),
    status: z.literal("failed").optional(),
    error_code: z.enum(["chunking_failed", "dense_embedding_failed", "sparse_embedding_failed", "invalid_dense_embeddings", "invalid_sparse_embeddings", "persistence_failed"]),
  });

export const IndexRequestSchema = z.object({
    content: z.string(),
    source_path: z.string(),
    source_type: z.string().nullable().optional(),
    namespace: z.string().optional(),
    project: z.string().nullable().optional(),
    stream: z.string().nullable().optional(),
    max_tokens: z.number().int().optional(),
    overlap_tokens: z.number().int().optional(),
  });

export const BatchIndexRequestSchema = z.object({
    documents: z.array(IndexRequestSchema),
  });

export const BatchIndexSucceededSchema = z.object({
    source_path: z.string(),
    status: z.literal("succeeded").optional(),
    chunks_indexed: z.number().int(),
  });

export const BatchIndexResponseSchema = z.object({
    results: z.array(z.union([BatchIndexSucceededSchema, BatchIndexFailedSchema])),
  });

export const BoostScoreSchema = z.object({
    chunk_id: z.string(),
    source_path: z.string(),
    edge_count: z.number().int(),
    avg_edge_weight: z.number(),
    boost_score: z.number(),
  });

export const CapabilityProjectionReceiptSchema = z.object({
    schema_version: z.literal(1).optional(),
    source_authority: z.literal("postgres").optional(),
    projection_only: z.literal(true).optional(),
    authorization_effect: z.literal("none").optional(),
    authorization_eligible: z.literal(false).optional(),
    tenant_id: z.string(),
    revision: z.number().int(),
    digest: z.string(),
    source_path: z.string(),
    namespace: z.string(),
    chunks_indexed: z.number().int(),
    strategy_used: z.string(),
  });

export const ProjectedCapabilitySchema = z.object({
    skill: z.string(),
    action: z.string(),
    version: z.number().int(),
  });

export const CapabilityProjectionRequestSchema = z.object({
    schema_version: z.literal(1),
    source_authority: z.literal("postgres"),
    tenant_id: z.string(),
    revision: z.number().int(),
    digest: z.string(),
    role: z.string(),
    task: z.string(),
    capability: ProjectedCapabilitySchema,
  });

export const SectionMetaSchema = z.object({
    doc_id: z.string().optional(),
    heading_path: z.array(z.string()),
    depth: z.number().int(),
    anchor: z.string(),
    anchor_path: z.array(z.string()),
    section_key: z.string(),
    schema_version: z.number().int().optional(),
  });

export const ChunkMetadataSchema = z.object({
    source_path: z.string(),
    source_type: z.string(),
    heading_hierarchy: z.array(z.string()).optional(),
    frontmatter: z.record(z.string(), z.unknown()).optional(),
    wikilinks: z.array(z.string()).optional(),
    tags: z.array(z.string()).optional(),
    language: z.string().nullable().optional(),
    section: SectionMetaSchema.nullable().optional(),
  });

export const ChunkSchema = z.object({
    id: z.string().optional(),
    content: z.string(),
    chunk_index: z.number().int(),
    parent_id: z.string().nullable().optional(),
    token_count: z.number().int().optional(),
    metadata: ChunkMetadataSchema,
    content_hash: z.string().optional(),
  });

export const ChunkLookupResultSchema = z.object({
    chunk_id: z.string(),
    chunk_index: z.number().int(),
    source_path: z.string(),
    source_type: z.string(),
    content_preview: z.string().optional(),
    metadata: z.record(z.string(), z.unknown()).optional(),
  });

export const ChunkManifestEntrySchema = z.object({
    chunk_id: z.string(),
    offset_start: z.number().int(),
    offset_end: z.number().int(),
  });

export const ChunkRequestSchema = z.object({
    content: z.string(),
    source_path: z.string().optional(),
    source_type: z.string().nullable().optional(),
    max_tokens: z.number().int().optional(),
    overlap_tokens: z.number().int().optional(),
    embed: z.boolean().optional(),
  });

export const ChunkResponseSchema = z.object({
    chunks: z.array(ChunkSchema),
    total_chunks: z.number().int(),
    total_tokens: z.number().int(),
    strategy_used: z.string(),
  });

export const CitationSchema = z.object({
    schema_version: z.number().int().optional(),
    chunk_id: z.string(),
    source_path: z.string(),
    source_type: z.string(),
    chunk_index: z.number().int(),
    heading_hierarchy: z.array(z.string()).optional(),
    relevance_score: z.number(),
    score_kind: z.enum(["rrf", "colbert_rerank"]),
  });

export const CrossReferenceSchema = z.object({
    chunk_id_a: z.string(),
    chunk_id_b: z.string(),
    similarity: z.number(),
    source_path_a: z.string(),
    source_path_b: z.string(),
    suggested_edge_type: z.string().optional(),
  });

export const DeleteSourceRequestSchema = z.object({
    namespace: z.string(),
    source_path: z.string(),
  });

export const DeleteSourceResponseSchema = z.object({
    namespace: z.string(),
    source_path: z.string(),
    chunks_deleted: z.number().int(),
  });

export const DreamAnalysisRequestSchema = z.object({
    namespace: z.string(),
    min_similarity: z.number().optional(),
    dedup_threshold: z.number().optional(),
    max_results_per_type: z.number().int().optional(),
    stale_days: z.number().int().optional(),
    include_boost: z.boolean().optional(),
  });

export const DuplicatePairSchema = z.object({
    chunk_id_a: z.string(),
    chunk_id_b: z.string(),
    similarity: z.number(),
    source_path_a: z.string(),
    source_path_b: z.string(),
    content_preview_a: z.string(),
    content_preview_b: z.string(),
  });

export const OrphanChunkSchema = z.object({
    chunk_id: z.string(),
    source_path: z.string(),
    edge_count: z.number().int(),
    created_at: z.string(),
  });

export const StaleChunkSchema = z.object({
    chunk_id: z.string(),
    source_path: z.string(),
    days_since_update: z.number().int(),
    edge_count: z.number().int(),
  });

export const DreamAnalysisResultSchema = z.object({
    namespace: z.string(),
    duplicates: z.array(DuplicatePairSchema),
    cross_references: z.array(CrossReferenceSchema),
    orphans: z.array(OrphanChunkSchema),
    stale: z.array(StaleChunkSchema),
    boosts: z.array(BoostScoreSchema),
    stats: z.record(z.string(), z.unknown()),
  });

export const EdgeCreateSchema = z.object({
    source_chunk_id: z.string(),
    target_chunk_id: z.string(),
    edge_type: z.string(),
    weight: z.number().optional(),
    created_by: z.string().optional(),
  });

export const EdgeCreateByPathSchema = z.object({
    source_path: z.string(),
    target_path: z.string(),
    edge_type: z.string(),
    weight: z.number().optional(),
    created_by: z.string().optional(),
    source_chunk_index: z.number().int().optional(),
    target_chunk_index: z.number().int().optional(),
  });

export const EdgeCreateByPathResponseSchema = z.object({
    created: z.number().int(),
    not_found: z.array(z.string()),
  });

export const EdgeInfoSchema = z.object({
    id: z.number().int(),
    source_chunk_id: z.string(),
    target_chunk_id: z.string(),
    edge_type: z.string(),
    weight: z.number(),
    created_by: z.string(),
    created_at: z.string(),
  });

export const EntitySchema = z.object({
    name: z.string(),
    entity_type: z.string(),
    description: z.string().nullable().optional(),
    properties: z.record(z.string(), z.unknown()).optional(),
  });

export const EntityEdgeSchema = z.object({
    source: z.string(),
    target: z.string(),
    relation: z.string(),
    weight: z.number().optional(),
  });

export const FactTypeSchema = z.enum(["summary", "contradiction", "derived_relation"]);

export const FeederCapabilityResponseSchema = z.object({
    schema_version: z.literal(1).optional(),
    namespaces: z.array(z.string()),
  });

export const OffsetRangeSchema = z.object({
    offset_start: z.number().int(),
    offset_end: z.number().int(),
  });

export const ParentOfChunkRangeSchema = z.object({
    parent_of_chunk: z.string(),
  });

export const FetchRequestSchema = z.object({
    by: z.enum(["document_id", "source_id", "chunk_id"]),
    id: z.string(),
    range: z.union([z.literal("full"), ParentOfChunkRangeSchema, OffsetRangeSchema]).optional(),
    include: z.array(z.enum(["content", "provenance"])).optional(),
  });

export const InjectionSignalSchema = z.object({
    flag: z.boolean().optional(),
    risk_score: z.number().int().optional(),
    patterns: z.array(z.string()).optional(),
  });

export const FetchResponseSchema = z.object({
    source_id: z.string(),
    path: z.string(),
    content: z.string(),
    content_len_tokens: z.number().int(),
    content_hash: z.string(),
    index_snapshot_id: z.string(),
    indexed_at: z.string(),
    embedding_model_id: z.string(),
    namespace: z.string(),
    trust_class: z.enum(["skill", "evidence"]),
    chunk_manifest: z.array(ChunkManifestEntrySchema).optional(),
    stale: z.boolean().optional(),
    trust_tier: z.enum(["raw", "curated"]).optional(),
    injection: InjectionSignalSchema.optional(),
    content_exact: z.boolean().optional(),
  });

export const SearchResultSchema = z.object({
    chunk_id: z.string(),
    content: z.string().optional(),
    source_path: z.string(),
    source_type: z.string(),
    chunk_index: z.number().int(),
    score: z.number(),
    namespace: z.string(),
    project: z.string().nullable().optional(),
    metadata: z.record(z.string(), z.unknown()).optional(),
    heading_hierarchy: z.array(z.string()).optional(),
    citation: CitationSchema.nullable().optional(),
    content_hash: z.string().optional(),
    source_id: z.string().optional(),
    trust_tier: z.enum(["raw", "curated"]).optional(),
    injection: InjectionSignalSchema.nullable().optional(),
  });

export const GroupedSearchResultSchema = z.object({
    group_key: z.string(),
    doc_id: z.string().optional(),
    score: z.number(),
    representative: SearchResultSchema,
    member_chunk_ids: z.array(z.string()).optional(),
    member_count: z.number().int().optional(),
  });

export const ValidationErrorSchema = z.object({
    loc: z.array(z.union([z.string(), z.number().int()])),
    msg: z.string(),
    type: z.string(),
    input: z.unknown().optional(),
    ctx: z.record(z.string(), z.unknown()).optional(),
  });

export const HTTPValidationErrorSchema = z.object({
    detail: z.array(ValidationErrorSchema).optional(),
  });

export const IndexResponseSchema = z.object({
    chunks_indexed: z.number().int(),
    source_path: z.string(),
    namespace: z.string(),
    strategy_used: z.string(),
  });

export const NamespaceStatsSchema = z.object({
    name: z.string(),
    chunk_count: z.number().int(),
    project_count: z.number().int(),
  });

export const IndexStatsSchema = z.object({
    total_chunks: z.number().int(),
    total_namespaces: z.number().int(),
    total_projects: z.number().int(),
    namespaces: z.array(NamespaceStatsSchema).optional(),
  });

export const StructuredGraphEdgeSchema = z.object({
    source: z.string(),
    target: z.string(),
    relation: z.string(),
    weight: z.literal(1.0).optional(),
  });

export const StructuredGraphEntitySchema = z.object({
    name: z.string(),
    entity_type: z.string(),
    description: z.string().nullable().optional(),
    properties: z.record(z.string(), z.unknown()).optional(),
  });

export const StructuredGraphSchema = z.object({
    schema_version: z.literal(1),
    content_hash: z.string(),
    entities: z.array(StructuredGraphEntitySchema).optional(),
    edges: z.array(StructuredGraphEdgeSchema).optional(),
  });

export const IngestRequestSchema = z.object({
    content: z.string(),
    source_path: z.string(),
    namespace: z.string().optional(),
    project: z.string().nullable().optional(),
    structured_graph: StructuredGraphSchema.nullable().optional(),
  });

export const JobStatusSchema = z.enum(["pending", "chunking", "extracting", "deduping", "done", "partial", "failed"]);

export const IngestResponseSchema = z.object({
    job_id: z.string(),
    status: JobStatusSchema,
    entities_upserted: z.number().int().optional(),
    edges_upserted: z.number().int().optional(),
    idempotent_noop: z.boolean().optional(),
    indexed: z.boolean().optional(),
    total_chunks: z.number().int().optional(),
    enrichment: z.enum(["complete", "failed", "not_applicable"]).optional(),
    enrichment_error: z.string().nullable().optional(),
  });

export const LtmJobSchema = z.object({
    id: z.string(),
    namespace: z.string(),
    source_path: z.string(),
    status: JobStatusSchema.optional(),
    current_step: z.string().nullable().optional(),
    total_chunks: z.number().int().optional(),
    processed_chunks: z.number().int().optional(),
    error: z.string().nullable().optional(),
  });

export const MemoryRecordSchema = z.object({
    content: z.string(),
    actor: z.string(),
    memory_type: z.string().optional(),
    namespace: z.string().optional(),
    project: z.string().nullable().optional(),
    tags: z.array(z.string()).optional(),
    importance: z.number().optional(),
    valid_from: z.string().nullable().optional(),
    valid_until: z.string().nullable().optional(),
    source_ref: z.string().nullable().optional(),
  });

export const MemoryBulkRequestSchema = z.object({
    memories: z.array(MemoryRecordSchema),
  });

export const MemoryBulkResponseSchema = z.object({
    indexed: z.number().int(),
    memory_ids: z.array(z.string()),
  });

export const MemoryIndexResponseSchema = z.object({
    memory_id: z.string(),
    chunk_id: z.string(),
    namespace: z.string(),
  });

export const MemoryRecallRequestSchema = z.object({
    query: z.string(),
    namespace: z.string().nullable().optional(),
    project: z.string().nullable().optional(),
    actor: z.string().nullable().optional(),
    memory_type: z.string().nullable().optional(),
    limit: z.number().int().optional(),
    min_score: z.number().optional(),
    include_expired: z.boolean().optional(),
    importance_boost: z.boolean().optional(),
  });

export const MemoryRecallResultSchema = z.object({
    memory_id: z.string(),
    content: z.string(),
    actor: z.string(),
    memory_type: z.string(),
    importance: z.number(),
    score: z.number(),
    namespace: z.string(),
    project: z.string().nullable().optional(),
    tags: z.array(z.string()).optional(),
    valid_from: z.string().nullable().optional(),
    valid_until: z.string().nullable().optional(),
    source_ref: z.string().nullable().optional(),
    created_at: z.string().nullable().optional(),
  });

export const MemoryRecallResponseSchema = z.object({
    results: z.array(MemoryRecallResultSchema),
    total: z.number().int(),
    query: z.string(),
    search_time_ms: z.number(),
  });

export const MemoryStatsSchema = z.object({
    total_memories: z.number().int(),
    by_namespace: z.record(z.string(), z.number().int()).optional(),
    by_actor: z.record(z.string(), z.number().int()).optional(),
    by_type: z.record(z.string(), z.number().int()).optional(),
  });

export const MetaFactSchema = z.object({
    id: z.string().nullable().optional(),
    namespace: z.string(),
    fact_type: FactTypeSchema,
    content: z.string(),
    source_chunk_ids: z.array(z.string()),
    entity_ids: z.array(z.string()).optional(),
    depth: z.number().int().optional(),
    derived_at: z.string().datetime().nullable().optional(),
    model_used: z.string(),
    reflect_run_id: z.string().nullable().optional(),
    properties: z.record(z.string(), z.unknown()).optional(),
  });

export const NamespaceCreateSchema = z.object({
    name: z.string(),
    description: z.string().nullable().optional(),
  });

export const NamespaceInfoSchema = z.object({
    id: z.number().int(),
    name: z.string(),
    description: z.string().nullable().optional(),
    chunk_count: z.number().int().optional(),
  });

export const OutlineNodeSchema = z.lazy(() => z.object({
    title: z.string(),
    anchor: z.string(),
    depth: z.number().int(),
    section_key: z.string(),
    chunk_ids: z.array(z.string()).optional(),
    children: z.array(OutlineNodeSchema).optional(),
  }));

export const OutlineResponseSchema = z.object({
    source_path: z.string(),
    namespace: z.string(),
    doc_id: z.string(),
    total_chunks: z.number().int(),
    outline: z.array(OutlineNodeSchema).optional(),
  });

export const RecallRequestSchema = z.object({
    query: z.string(),
    namespace: z.string().nullable().optional(),
    limit: z.number().int().optional(),
    expand_entities: z.boolean().optional(),
    min_score: z.number().optional(),
    as_of: z.string().datetime().nullable().optional(),
    time_range: z.array(z.unknown()).nullable().optional(),
    temporal_boost: z.number().optional(),
  });

export const RecallResultSchema = z.object({
    chunk_id: z.string(),
    content: z.string(),
    source_path: z.string(),
    score: z.number(),
    namespace: z.string(),
    project: z.string().nullable().optional(),
    metadata: z.record(z.string(), z.unknown()).optional(),
    entities: z.array(EntitySchema).optional(),
    relations: z.array(EntityEdgeSchema).optional(),
  });

export const RecallResponseSchema = z.object({
    results: z.array(RecallResultSchema),
    total: z.number().int(),
    query: z.string(),
    search_time_ms: z.number(),
  });

export const ReflectRequestSchema = z.object({
    namespace: z.string().optional(),
    since: z.string().datetime().nullable().optional(),
    max_chunks: z.number().int().nullable().optional(),
    dry_run: z.boolean().optional(),
  });

export const ReflectRunSummarySchema = z.object({
    run_id: z.string(),
    status: z.string(),
    chunks_scanned: z.number().int(),
    meta_facts_created: z.number().int(),
    cost_usd: z.number(),
    req_count: z.number().int(),
    abort_reason: z.string().nullable().optional(),
    duration_ms: z.number(),
  });

export const ReflectResponseSchema = z.object({
    summary: ReflectRunSummarySchema,
    preview: z.array(MetaFactSchema).nullable().optional(),
  });

export const RollbackCapabilityResponseSchema = z.object({
    schema_version: z.literal(1).optional(),
    namespaces: z.array(z.string()),
    operator: z.boolean(),
  });

export const SearchRequestSchema = z.object({
    query: z.string(),
    namespace: z.string().nullable().optional(),
    project: z.string().nullable().optional(),
    source_type: z.string().nullable().optional(),
    limit: z.number().int().optional(),
    min_score: z.number().optional(),
    include_content: z.boolean().optional(),
    group_by: z.enum(["document", "section"]).nullable().optional(),
    maturity: z.enum(["draft", "validated", "production"]).nullable().optional(),
  });

export const SearchResponseSchema = z.object({
    results: z.union([z.array(SearchResultSchema), z.array(GroupedSearchResultSchema)]),
    total: z.number().int(),
    query: z.string(),
    search_time_ms: z.number(),
  });

export const SectionBreadcrumbSchema = z.object({
    title: z.string(),
    section_key: z.string(),
    depth: z.number().int(),
  });

export const SectionSelfSchema = z.object({
    title: z.string(),
    section_key: z.string(),
    depth: z.number().int(),
    chunk_ids: z.array(z.string()).optional(),
  });

export const SectionContextSchema = z.object({
    chunk_id: z.string(),
    doc_id: z.string(),
    section_key: z.string(),
    ancestors: z.array(SectionBreadcrumbSchema).optional(),
    self: SectionSelfSchema,
    siblings: z.array(SectionBreadcrumbSchema).optional(),
    children: z.array(SectionBreadcrumbSchema).optional(),
  });

export const SourceDeleteRequestSchema = z.object({
    namespace: z.string(),
    source_path: z.string(),
  });

export const SourceDeleteResponseSchema = z.object({
    chunks_deleted: z.number().int(),
    entity_sources_deleted: z.number().int(),
    edge_sources_deleted: z.number().int(),
    edges_deleted: z.number().int(),
    entities_deleted: z.number().int(),
    idempotent_noop: z.boolean(),
  });
