#!/usr/bin/env python3
"""Emit the service's HTTP contract as TypeScript declarations the ecosystem's verifier can diff.

WHY TYPESCRIPT IN A PYTHON REPOSITORY. The graph-verified-change mandate (DEC-AUP-0008) verifies a
`provides_route` edge with `contract_diff`, and the vendored verifier reads contracts out of CODE,
from `*.ts` files only (`.github/graph-admission/tools/graph/contract_diff.py:236 ts_paths`), in
four kinds: zod constants, class-validator DTOs, string-literal union type aliases and TS enums
(:356 `CONTRACT_KINDS`). It has no pydantic extractor and no OpenAPI reader — its own selftest says
so in as many words (:1747, "kind `openapi` NOT MEASURED"). A committed `openapi.json` would
therefore still leave every route `not_measured` with `NO_CONTRACTS` (:1503), which is the state
A2-308 measured: 36 of 41 unmeasured entities were routes, for that one reason.

So the wire contract is PUBLISHED in the shape the verifier reads. The source of truth stays the
FastAPI application: this file never invents a schema, it transcribes `app.openapi()`. The
committed artefact is checked against a fresh generation by `tests/test_http_contract.py`, so a
pydantic model that changes without the contract changing with it is a red test, and a route whose
response model loses a field is a `FIELD_REMOVED` breaking change on the next admission run.

    tools/gen_http_contract.py [--out contracts/http/scrutator-http.contract.ts] [--check]

stdlib + the application's own dependencies; no network, no database.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

HEADER = """// GENERATED BY tools/gen_http_contract.py — DO NOT EDIT BY HAND.
//
// The HTTP contract of Scrutator, transcribed from the FastAPI application's own OpenAPI document
// (`scrutator.health.app.openapi()`), in the only shape the graph-verified-change verifier can
// diff: zod declarations and a string-literal union of the served routes
// (contract_diff.py reads *.ts only; it has no pydantic or OpenAPI extractor).
//
// Regenerate with `python3 tools/gen_http_contract.py`; `tests/test_http_contract.py` fails if this
// file and the application disagree.
//
// It is also a usable contract: a TypeScript consumer of this service can import these schemas.

import { z } from "zod";
"""

IDENT_RE = re.compile(r"[^A-Za-z0-9_]")


def symbol_of(name: str) -> str:
    """The exported symbol for a component schema.

    `contract_diff.Extractor.direction_of` reads the DIRECTION of a contract off its symbol name:
    a symbol ending in Response/Result/Output/View is an output contract, one ending in
    Request/Body/Query/Payload/Dto is an input contract, anything else is bidirectional (the
    conservative reading, where a widening counts as breaking). The pydantic class names already
    carry that information — `SearchRequest`, `ChunkResponse` — so the suffix is preserved and
    `Schema` (which the verifier strips) is appended.
    """
    return IDENT_RE.sub("_", name) + "Schema"


class Emitter:
    def __init__(self, schemas: dict):
        self.schemas = schemas
        self.deps: dict[str, set[str]] = {}
        self.current: str | None = None

    # ---- JSON Schema (pydantic flavour) -> zod expression -------------------------------------
    def ref(self, ref: str) -> str:
        name = ref.rsplit("/", 1)[-1]
        if name not in self.schemas:
            return "z.unknown()"
        if self.current is not None:
            self.deps.setdefault(self.current, set()).add(name)
        return symbol_of(name)

    def expr(self, node, indent: int = 1) -> str:
        if not isinstance(node, dict) or node == {}:
            return "z.unknown()"
        if "$ref" in node:
            return self.ref(node["$ref"])
        if "allOf" in node and len(node["allOf"]) == 1 and not node.get("type"):
            return self.expr(node["allOf"][0], indent)
        for key in ("anyOf", "oneOf"):
            if key in node:
                return self.union(node[key], indent)
        if "const" in node:
            return f"z.literal({json.dumps(node['const'])})"
        if "enum" in node and node.get("type") in (None, "string"):
            values = ", ".join(json.dumps(v) for v in node["enum"])
            return f"z.enum([{values}])"
        kind = node.get("type")
        if isinstance(kind, list):  # JSON-Schema type unions
            return self.union([{"type": t} for t in kind], indent)
        if kind == "array":
            return f"z.array({self.expr(node.get('items') or {}, indent)})"
        if kind == "object" or "properties" in node:
            return self.obj(node, indent)
        if kind == "integer":
            return "z.number().int()"
        if kind == "number":
            return "z.number()"
        if kind == "boolean":
            return "z.boolean()"
        if kind == "null":
            return "z.null()"
        if kind == "string":
            fmt = {
                "uuid": "z.string().uuid()",
                "email": "z.string().email()",
                "date-time": "z.string().datetime()",
                "uri": "z.string().url()",
            }
            return fmt.get(node.get("format", ""), "z.string()")
        return "z.unknown()"

    def union(self, options: list, indent: int) -> str:
        """`X | null` is a nullable X, not a two-branch union: pydantic spells every `T | None` that
        way and a literal transcription would bury the real shape under `z.union([...])`."""
        parts = [o for o in options if not (isinstance(o, dict) and o.get("type") == "null")]
        nullable = len(parts) != len(options)
        if not parts:
            return "z.null()"
        if len(parts) == 1:
            inner = self.expr(parts[0], indent)
        else:
            inner = "z.union([" + ", ".join(self.expr(p, indent) for p in parts) + "])"
        return inner + (".nullable()" if nullable else "")

    def obj(self, node: dict, indent: int) -> str:
        props = node.get("properties") or {}
        if not props:
            extra = node.get("additionalProperties")
            values = self.expr(extra, indent) if isinstance(extra, dict) and extra else "z.unknown()"
            return f"z.record(z.string(), {values})"
        required = set(node.get("required") or [])
        pad, close = "  " * (indent + 1), "  " * indent
        lines = []
        for key in props:
            value = self.expr(props[key], indent + 1)
            if key not in required:
                value += ".optional()"
            name = key if re.fullmatch(r"[A-Za-z_$][\w$]*", key) else json.dumps(key)
            lines.append(f"{pad}{name}: {value},")
        return "z.object({\n" + "\n".join(lines) + f"\n{close}}})"

    # ---- ordering ------------------------------------------------------------------------------
    def order(self) -> tuple[list[str], set[str]]:
        """Declaration order, and the names that must be `z.lazy` because they sit in a cycle.

        `const` is not hoisted, so a schema referenced before it is declared would be a runtime
        temporal-dead-zone error for a real consumer. Recursive models (a tree of chunks) cannot be
        ordered at all, and get `z.lazy(() => X)`, which `contract_diff.zod` unwraps (:539)."""
        order, state, lazy = [], {}, set()

        def visit(name: str, stack: tuple):
            if state.get(name) == "done":
                return
            if state.get(name) == "open":
                lazy.add(name)
                return
            state[name] = "open"
            for dep in sorted(self.deps.get(name, ())):
                visit(dep, stack + (name,))
            state[name] = "done"
            order.append(name)

        for name in sorted(self.schemas):
            visit(name, ())
        return order, lazy


def route_union(paths: dict) -> str:
    """The served route surface as a string-literal union type alias.

    This is the part of the contract no type-checker and no unit test can see. The AUP-GRAPH-007
    calibration says so with numbers: 50 of the 65 route mutants it generated were path or verb
    rewrites, and it could not measure the `provides_route` class at all
    (`verifier-matrix.v1.json` → `provides_route.calibration`). Published as a union, a deleted or
    renamed route is an `ENUM_VALUE_REMOVED` — breaking in every direction — and an added route is
    an `ENUM_VALUE_ADDED`, which is compatible for an input contract, hence the `Request` suffix:
    what this enumerates is the set of route requests the service accepts.
    """
    members = sorted(
        f"{method.upper()} {path}"
        for path, ops in paths.items()
        for method in ops
        if method.lower() in ("get", "post", "put", "patch", "delete", "head", "options")
    )
    body = "\n".join(f"  | {json.dumps(m)}" for m in members)
    return "export type ScrutatorRouteRequest =\n" + body + ";\n"


def render(document: dict) -> str:
    schemas = document.get("components", {}).get("schemas", {})
    emitter = Emitter(schemas)
    bodies = {}
    for name in sorted(schemas):
        emitter.current = name
        bodies[name] = emitter.expr(schemas[name])
    emitter.current = None
    order, lazy = emitter.order()

    out = [HEADER, "", route_union(document.get("paths") or {}), ""]
    for name in order:
        body = bodies[name]
        if name in lazy:
            # A recursive schema needs both the runtime thunk and an explicit type annotation:
            # without one `tsc` answers TS7022 ("implicitly has type any ... referenced in its own
            # initializer") and the type_check verifier of the same route would go red.
            body = f"z.lazy(() => {body})"
            out.append(f"export const {symbol_of(name)}: z.ZodType = {body};\n")
            continue
        out.append(f"export const {symbol_of(name)} = {body};\n")
    return "\n".join(out)


def build() -> str:
    from scrutator.health import app  # imported here: the CLI must be importable without the app

    return render(app.openapi())


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", default="contracts/http/scrutator-http.contract.ts")
    parser.add_argument(
        "--check", action="store_true", help="exit 1 if the committed file differs from a fresh generation"
    )
    args = parser.parse_args(argv)
    generated = build()
    target = Path(args.out)
    if args.check:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current != generated:
            print(f"{target}: out of date — run `python3 tools/gen_http_contract.py`", file=sys.stderr)
            return 1
        print(f"{target}: matches the application")
        return 0
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(generated, encoding="utf-8")
    print(f"{target}: {len(generated.splitlines())} lines")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
